Celery 3.0-->3.1 + Logging
Upgraded from celery 3.0 to celery 3.1
Added lines for improved task logging
	modified:   atmosphere/__init__.py
	new file:   atmosphere/celery.py
	modified:   atmosphere/settings/__init__.py
	modified:   extras/init.d/atmosphere
	new file:   extras/init.d/celerybeat.default
	modified:   extras/init.d/celeryd.default
	new file:   extras/init.d/ubuntu.celerybeat
	modified:   extras/init.d/ubuntu.celeryd
	modified:   requirements.txt

diff --git a/extras/init.d/atmosphere b/extras/init.d/atmosphere
--- a/extras/init.d/atmosphere
+++ b/extras/init.d/atmosphere
@@ -14,6 +14,15 @@ CELERY_DEFAULT="/etc/default/celeryd"
 
 if [ ! -f  $CELERY_INITD ]; then
     echo "Expected celery service file $CELERY_INITD missing"
+    echo "For Ubuntu:"
+    echo "ln -s /opt/dev/atmosphere/extras/init.d/ubuntu.celeryd $CELERY_DEFAULT"
+    echo "For CentOS:"
+    echo "ln -s /opt/dev/atmosphere/extras/init.d/centos.celeryd $CELERY_DEFAULT"
+    exit 1
+elif [ ! -f  $CELERYBEAT_INITD ]; then
+    echo "Expected celery service file $CELERYBEAT_INITD missing"
+    echo "For Ubuntu:"
+    echo "ln -s /opt/dev/atmosphere/extras/init.d/ubuntu.celerybeat $CELERY_DEFAULT"
     exit 1
 elif [ ! -f  $CELERY_DEFAULT ]; then
     echo "Celery config file $CELERY_DEFAULT missing."
@@ -28,6 +37,7 @@ case "$1" in
 status)
     service apache2 status
     service celeryd status
+    service celerybeat status
 ;;
 start)
     printf "Starting $NAME...\n"
@@ -39,6 +49,8 @@ start)
     service $WEB_SERVICE start
     printf "Starting Celery..\n"
     service celeryd start
+    printf "Starting Celerybeat..\n"
+    service celerybeat start
 ;;
 stop)
     printf "Stopping $NAME...\n"
@@ -50,6 +62,7 @@ stop)
     service $WEB_SERVICE stop
     printf "Stopping Celery..\n"
     service celeryd stop
+    service celerybeat stop
 ;;
 
 restart)
@@ -59,6 +72,7 @@ restart)
     fi
     service apache2 restart
     service celeryd restart
+    service celerybeat restart
 ;;
 
 *)
