Sanity checks added to atmosphere service

diff --git a/extras/init.d/atmosphere b/extras/init.d/atmosphere
--- a/extras/init.d/atmosphere
+++ b/extras/init.d/atmosphere
@@ -6,6 +6,16 @@
 
 NAME='Atmosphere'
 DESC="Deals with the workflow associated with running atmospehre as a service"
+CELERY_SERVICE="/etc/init.d/celeryd"
+APACHE_SERVICE="/etc/init.d/apache2"
+
+if [ ! -f  $CELERY_SERVICE ]; then
+    echo "Expected celery service file $CELERY_SERVICE missing"
+    exit 1
+elif [ ! -f  $APACHE_SERVICE ]; then
+    echo "Expected apache service file $APACHE_SERVICE missing"
+    exit 1
+fi
 
 case "$1" in
 status)
@@ -13,6 +23,10 @@ status)
     service celeryd status
 ;;
 start)
+    if [[ $EUID -ne 0 ]]; then
+        echo "You must be a root user to start atmosphere"
+        exit 1
+    fi
     printf "Starting $NAME...\n"
     printf "Starting Apache..\n"
     service apache2 start
@@ -20,6 +34,10 @@ start)
     service celeryd start
 ;;
 stop)
+    if [[ $EUID -ne 0 ]]; then
+        echo "You must be a root user to stop atmosphere"
+        exit 1
+    fi
     printf "Stopping $NAME...\n"
     printf "Stopping Apache..\n"
     service apache2 stop
