More changes to the atmosphere script. Should be error-free now.. Also added the instance migrations necessary for the new shell/vnc link testing methods.

diff --git a/extras/init.d/atmosphere b/extras/init.d/atmosphere
--- a/extras/init.d/atmosphere
+++ b/extras/init.d/atmosphere
@@ -6,14 +6,21 @@
 
 NAME='Atmosphere'
 DESC="Deals with the workflow associated with running atmospehre as a service"
-CELERY_SERVICE="/etc/init.d/celeryd"
-APACHE_SERVICE="/etc/init.d/apache2"
 
-if [ ! -f  $CELERY_SERVICE ]; then
-    echo "Expected celery service file $CELERY_SERVICE missing"
+WEB_SERVICE="apache2" # could be httpd on centos..
+WEB_INITD="/etc/init.d/$WEB_SERVICE"
+CELERY_INITD="/etc/init.d/celeryd"
+CELERY_DEFAULT="/etc/default/celeryd"
+
+if [ ! -f  $CELERY_INITD ]; then
+    echo "Expected celery service file $CELERY_INITD missing"
     exit 1
-elif [ ! -f  $APACHE_SERVICE ]; then
-    echo "Expected apache service file $APACHE_SERVICE missing"
+elif [ ! -f  $CELERY_DEFAULT ]; then
+    echo "Celery config file $CELERY_DEFAULT missing."
+    echo "ln -s /opt/dev/atmosphere/extras/init.d/celeryd.default $CELERY_DEFAULT"
+    exit 1
+elif [ ! -f  $WEB_INITD ]; then
+    echo "Expected apache service file $WEB_INITD missing"
     exit 1
 fi
 
@@ -23,24 +30,24 @@ status)
     service celeryd status
 ;;
 start)
+    printf "Starting $NAME...\n"
     if [[ $EUID -ne 0 ]]; then
         echo "You must be a root user to start atmosphere"
         exit 1
     fi
-    printf "Starting $NAME...\n"
-    printf "Starting Apache..\n"
-    service apache2 start
+    printf "Starting $WEB_SERVICE\n"
+    service $WEB_SERVICE start
     printf "Starting Celery..\n"
     service celeryd start
 ;;
 stop)
+    printf "Stopping $NAME...\n"
     if [[ $EUID -ne 0 ]]; then
         echo "You must be a root user to stop atmosphere"
         exit 1
     fi
-    printf "Stopping $NAME...\n"
-    printf "Stopping Apache..\n"
-    service apache2 stop
+    printf "Stopping $WEB_SERVICE\n"
+    service $WEB_SERVICE stop
     printf "Stopping Celery..\n"
     service celeryd stop
 ;;
